"use client";

/**
 * HypothesisList
 *
 * Displays ranked hypotheses generated by the Hypothesizer agent.
 * Each hypothesis shows:
 *   - Text description
 *   - Surprise score (KL divergence x significance x effect size)
 *   - Status: pending | testing | validated | rejected
 *   - Grade badge (A/B/C) after validation
 *
 * Hypotheses ranked by surprise score descending.
 * Active hypothesis (being tested) highlighted.
 * Rejected hypotheses grayed out but visible.
 */

import type { Hypothesis, PipelineStage } from "@/app/page";

interface HypothesisListProps {
  hypotheses: Hypothesis[];
  activeStage: PipelineStage;
}

export default function HypothesisList({
  hypotheses,
  activeStage,
}: HypothesisListProps) {
  const sorted = [...hypotheses].sort(
    (a, b) => b.surpriseScore - a.surpriseScore,
  );

  return (
    <div className="bg-zinc-900 rounded-xl p-6 border border-zinc-800">
      <h2 className="text-lg font-semibold mb-4">Hypotheses</h2>
      {sorted.length === 0 ? (
        <p className="text-zinc-500 text-sm">
          {activeStage === "profiling"
            ? "Profiling training artifacts..."
            : "Waiting for hypotheses..."}
        </p>
      ) : (
        <ul className="space-y-3">
          {sorted.map((h) => (
            <li
              key={h.id}
              className={`p-4 rounded-lg border ${
                h.status === "rejected"
                  ? "border-zinc-800 opacity-50"
                  : h.status === "validated"
                    ? "border-green-800 bg-green-950/30"
                    : h.status === "testing"
                      ? "border-indigo-700 bg-indigo-950/20"
                      : "border-zinc-800"
              }`}
            >
              <div className="flex justify-between items-start">
                <p className="text-sm">{h.text}</p>
                <div className="flex items-center gap-2 ml-4 shrink-0">
                  <span className="text-xs text-zinc-500">
                    {h.surpriseScore.toFixed(2)}
                  </span>
                  {h.grade && (
                    <span
                      className={`text-xs font-bold px-2 py-0.5 rounded ${
                        h.grade === "A"
                          ? "bg-green-900 text-green-300"
                          : h.grade === "B"
                            ? "bg-yellow-900 text-yellow-300"
                            : "bg-red-900 text-red-300"
                      }`}
                    >
                      {h.grade}
                    </span>
                  )}
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
