/**
 * sandbox.ts - E2B code interpreter integration for LITMUS.
 *
 * Executes Python code generated by the Experimenter agent
 * in a sandboxed environment. Returns stdout, stderr, and
 * any generated files (Plotly JSON, CSVs).
 *
 * E2B sandbox includes: numpy, pandas, scipy, statsmodels,
 * sklearn, torch, plotly, matplotlib.
 *
 * TODO: Wire to @e2b/code-interpreter SDK
 */

export interface SandboxResult {
  stdout: string;
  stderr: string;
  exitCode: number;
  files: { name: string; content: string }[];
  executionTime: number;
}

/**
 * Execute Python code in E2B sandbox.
 * Returns structured result with stdout, files, timing.
 */
export async function executeInSandbox(
  code: string,
): Promise<SandboxResult> {
  // TODO: Replace with actual E2B integration
  // const sandbox = await CodeInterpreter.create();
  // const execution = await sandbox.notebook.execCell(code);
  // await sandbox.close();

  console.warn("E2B sandbox not yet wired. Returning mock result.");

  return {
    stdout: "Mock execution result",
    stderr: "",
    exitCode: 0,
    files: [],
    executionTime: 0,
  };
}

/**
 * Execute experiment code and extract structured results.
 * Parses the Python script's JSON output for p-value, effect size, plot.
 */
export async function runExperiment(code: string): Promise<{
  pValue: number;
  effectSize: number;
  plotJson?: string;
  interpretation: string;
}> {
  const result = await executeInSandbox(code);

  if (result.exitCode !== 0) {
    throw new Error(`Experiment failed: ${result.stderr}`);
  }

  // Parse JSON from stdout (experimenter scripts print JSON as last line)
  try {
    const lines = result.stdout.trim().split("\n");
    const lastLine = lines[lines.length - 1];
    const parsed = JSON.parse(lastLine);
    return {
      pValue: parsed.p_value ?? 1.0,
      effectSize: parsed.effect_size ?? 0,
      plotJson: parsed.plot,
      interpretation: parsed.interpretation ?? "No interpretation provided.",
    };
  } catch {
    return {
      pValue: 1.0,
      effectSize: 0,
      interpretation: `Raw output: ${result.stdout.slice(0, 500)}`,
    };
  }
}
